
export const data = {
  news: [
    {
      id: 1,
      type: "news",
      heading: `Syed Sadiqali Shihab Thangal unveils Sibaq'22 Darul Huda National Arts fest logo`,
      slug: "sibaq-22-logo-is-revealed",
      news_content: `Sibaq '22,  biennial national arts fest of Darul Huda Islamic University, got its logo unveiled  by the hands of Syed Sadiqali Shihab Thangal . The ceremony was also attended by AP Unnikrishnan, Dr. Rafeeq Ali Hudawi Karimpanakkal, Academic Registrar of Darul Huda and Abdu shukoor Hudawi, Sibaq'22 Chairman. Sibaq '22 will be conducted in two phases, preliminary and final rounds. While the preliminary rounds are scheduled in Darul Huda's different UG campuses on 11,12,13 November, the final rounds of all sections will be staged in Darul Huda main campus on 1,2,3,4 December respectively. Compared to the previous years, Sibaq'22 is going to be a great event with varieties of programmes. More than 4000 candidates are expected to showcase their talents in a number of artistic, literary, and cultural items this year. The students from Darul Huda central campus and its 28 affiliated colleges, in and out of Kerala, and five off-campus centers will participate in the event.`,
      image: require("/public/assets/images/sibaq-logo-reveal-news.jpg")
        .default,
      image_caption: "Sibaq '22 logo is revealed",
      image_description: "  Sibaq '22 logo is revealed",
      date: "2022-10-11",
      tags: ["Logo", "Sadiqali Shihab Thangal"],
    },
    {
      id: 2,
      type: "news",
      heading: ` Sibaq '22 Gears up For Grand Finale on December`,
      slug: "Sibaq-22-Gears-up-For-Grand-Finale-on-December",
      news_content: `Sibaq, the national arts fest, organized by Darul Huda Islamic University, is all set to commence its final edition from December 1 to 4 at the varsity campus. The selected candidates from the primary rounds will make grand finale podiums engaged and enthralled.The sibaq will finish its elimination rounds of Bidayah and Ula within November 11-13 followed by the elimination round of Thaniya and Thanawiyya within November 18 to 20, held in six affiliated academies of DHIU after the competition of Y category. Darul Huda will be in spotlight as most awaited competition items under different venues; both indoor and  outdoor, will be progressing underway . The event will be highlighted for the participation of more than 9100 students and more than 4000 candidates in 360+items from 20+ states beginning with a huge procession marked by colourful manifestations of art under concerned institutions. 
            The hosting institution DHIU is full-fledged by its heartful prearrangement for the regional and national candidates. About three months in the making, the event focused on creating an art-oriented and Islamic-friendly fest in the values. As art can act as a mirror that reflects modern problems and a bridge between different cultural outlooks. The diversity of participants make this arts fest as the celebrations of richness and diversity of culture and creativity more than performing art.  Sibaq’22 with its vibrant  legacy upholds the stature of the charisma acquired by Darul Huda throughout it's history, creatively engaging in socio-cultural aspects. Sibaq'22 podiums will facilitate the candidates a distinctive platform to develop an constructive and competitive environment. The institution led procession will be succeeded by the flag hoisting and the  gathering. Darul Huda Islamic University has stretched its all managing directions to host the national arts fest.`,
      image: require("/public/assets/images/sibaq-gears-up.jpg").default,
      image_caption: "Sibaq '22 logo is revealed",
      image_description: `SIBAQ'22 GEARS UP FOR GRAND FINALE ON December `,
      date: "2022-10-18",
      tags: ["tag1", "tag2"],
    },
    {
      id: 3,
      type: "news",
      heading: ` Sibaq 2k22 website launched`,
      slug: "Sibaq-2k22-website-launched",
      news_content: `In an event which took place at Hadia CSE yesterday evening, Sayyid Moyeen Ali Shihab launched the official website of Sibaq'22, the national intercollegiate arts fest of Darul Huda Islamic University. The programme was also attended by Abdul shukoor Hudawi, PG Dean and Sibaq chairman, Darul Huda registrar Dr Rafeeq Ali Hudawi, Dr Ja'far kolathur Hudawi, Sibaq chief controller, Abdul Jaleel Hudawi and Aboobaker Hudawi. 

In the late session of the programme, Hadia conducted a SIBAQ workshop under the name "Barsaat" in which Dr Jameel Ahmed talked about 'Festive Aesthetics'. Dr Shareef Hudawi and Fahad Hudawi Puthanangadi also made the programme memorable and spoke about 'Arts culture and festivals' and 'The voice and beyond' respectively.`,
      image: require("/public/assets/images/1x1_4.jpg").default,
      image_caption: "Sibaq '22 logo is revealed",
      image_description: `SIBAQ 2K22 WEBSITE LAUNCHED`,
      date: "2022-10-19",
      tags: ["www.sibaq.in", "sibaq.in"],
    },
    {
      id: 4,
      type: "news",
      heading: `Hold your breath. It’s show time`,
      slug: "Hold-your-breath-Its-show-time",
      news_content: `The toll now can be heard right above the head as the elimination rounds of Sibaq national art fest are only days ahead. Within a week the contestants will be firing up the cylinders with full might only to roll up the mats for the ultimate face off. Participants are looked upon with higher expectations as each campus is valiantly trying to get the final glory. 
            Prior to that, the non stage programs will be commencing in coming week in 8 different centers across the state. Unlike from the previous Sibaqs, contestants from Fathima Zahrawiyya will be testing their might in these programs.
            However, all eyes are on the first rounds, beginning from 11th this month except for the Aliyah which will be at 18th, where more than 300 contestants eagerly trying to reap the results of their sleepless nights . It is more unlikely to be a walk in the park for each participants non of them are seemingly ready to compromise this for anything. Now buckle up and wait for the whistle.
            `,
      image: require("/public/assets/images/sibaq-gears-up.jpg").default,
      image_caption: "Hold your breath. It’s show time",
      image_description: `Hold your breath. It’s show time.`,
      date: "2022-11-08",
      tags: ["www.sibaq.in", "sibaq.in"],
    },
    {
      id: 5,
      type: "audio-broadcast",
      file: "/assets/audio/sibaq.MP3",
      heading: `Sibaq radio 0.6`,
      slug: "sibaq-radio-0-6",
      news_content: `This is how we reach out to you people with every breath of Sibaq 2022. The telling moments  will be recorded inch by inch as it progresses. The liveliness of Sibaq 2022 would flow into you. Just sit back and listen to the voice of Sibaq 2022 . Stay tuned`,
      image: require("/public/assets/images/sibaq-gears-up.jpg").default,
      image_caption: "",
      image_description: ``,
      date: "2022-11-10",
      tags: ["Sibaq radio 0.6", "sibaq.in"],
    },
    {
      id: 6,
      type: "yt-video",
      file: "gqDLPBULqAs",
      heading: `SIBAQ THEME SONG PUBLISHED`,
      slug: "sibaq-theme-song",
      news_content: `SIBAQ' 22 DARUL HUDA NATIONAL ARTS FEST | OFFICIAL THEME SONG`,
      image: require("/public/assets/images/sibaq-gears-up.jpg").default,
      image_caption: "",
      image_description: ``,
      date: "2022-11-11",
      tags: ["ThemeSong", "sibaq.in"],
    },
    {
      id: 7,
      type: "yt-video",
      file: "ATK7e7q4WJk",
      heading: `SIBAQ BIDAYA OFFICIAL THEME SONG`,
      slug: "sibaq-bidaya-theme-song",
      news_content: `SIBAQ'22 BIDAYA OFFICIAL THEME SONG | SHEIKH FAREED AULIYA DA'WA COLLEGE ODAMALA`,
      image: require("/public/assets/images/sibaq-gears-up.jpg").default,
      image_caption: "",
      image_description: ``,
      date: "2022-11-13",
      tags: ["ThemeSong", "sibaq.in"],
    },
    {
      id: 8,
      type: "yt-video",
      file: "Po-_55i3kHU",
      heading: `SIBAQ BIDAYA OFFICIAL THEME SONG`,
      slug: "sibaq-thaniyah-theme-song",
      news_content: `SIBAQ'22 THANIYAH OFFICIAL THEME SONG | DARUL IRFAN PANDIKKAD`,
      image: require("/public/assets/images/sibaq-gears-up.jpg").default,
      image_caption: "",
      image_description: ``,
      date: "2022-11-13",
      tags: ["ThemeSong", "sibaq.in"],
    },
    {
      id: 9,
      type: "yt-video",
      file: "XTj7tWXpltE",
      heading: `SIBAQ THANAWIYYA OFFICIAL THEME SONG`,
      slug: "sibaq-thanawiyya-theme-song",
      news_content: `SIBAQ'22 THANAWIYYA OFFICIAL THEME SONG | Manhajurrashd Islamic College`,
      image: require("/public/assets/images/sibaq-gears-up.jpg").default,
      image_caption: "",
      image_description: ``,
      date: "2022-11-13",
      tags: ["ThemeSong", "sibaq.in"],
    },
    {
      id: 10,
      type: "audio-broadcast",
      file: "/assets/audio/Sibaq radio episode 2.mp3",
      heading: `Sibaq radio 0.6 episode 2`,
      slug: "sibaq-radio-0-6-episode-2",
      news_content: ``,
      image: require("/public/assets/images/sibaq-gears-up.jpg").default,
      image_caption: "",
      image_description: ``,
      date: "2022-11-13",
      tags: ["RJ Shameem", "Sibaq radio 0.6", "sibaq.in"],
    },
    {
      id: 11,
      type: "audio-broadcast",
      file: "/assets/audio/episode3.mp3",
      heading: `Sibaq radio 0.6 episode 3`,
      slug: "sibaq-radio-0-6-episode-3",
      news_content: ``,
      image: require("/public/assets/images/sibaq-gears-up.jpg").default,
      image_caption: "",
      image_description: ``,
      date: "2022-11-20",
      tags: ["RJ Shameem", "Sibaq radio 0.6", "sibaq.in"],
    },
  ],

  notifications: [
    {
      id: 1,
      title: "Sibaq 2022 Logo launched",
      description: `Sibaq '22 logo was unveiled  by the hands of Syed Sadiqali Shihab Thangal .`,
      image: require("/public/assets/images/logo_rounded.png").default,
      link: "/news/sibaq-22-logo-is-revealed",
      date: "2022-10-11",
    },
    {
      id: 2,
      title: `Sibaq '22 Gears up For Grand Finale on December`,
      description:
        "Sibaq, the national arts fest, is now all set to commence its final edition from December 1 to 4 at the varsity campus.",
      image: require("/public/assets/images/logo_rounded.png").default,
      link: "/news/Sibaq-22-Gears-up-For-Grand-Finale-on-December",
      date: "2022-10-18",
    },
    {
      id: 3,
      title: `Sibaq 2k22 website launched`,
      description:
        "In an event which took place at Hadia CSE , Sayyid Moyeen Ali Shihab launched the official website.",
      image: require("/public/assets/images/logo_rounded.png").default,
      link: "/news/Sibaq-2k22-website-launched",
      date: "2022-10-19",
    },
    {
      id: 4,
      title: `Results are out now`,
      description:
        "Here is the much awaited first round results of Sibaq 2022. Go check it out now.",
      image: require("/public/assets/images/logo_rounded.png").default,
      link: "/public_portal/elimination_results",
      date: "2022-11-12",
    },
  ],
};
