import Head from "next/head";
import styles from "../styles/landing-page.module.css";

export default function LandingPage() {
  return (
    <div className="">
      <Head>
        <title>Sibaq-22</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.header}>
        <div className={styles.navbar}>
          <div className={styles.bars}>
            <div className={styles.bar}></div>
            <div className={styles.bar}></div>
            <div className={styles.bar}></div>
          </div>

        </div>
        <div className={styles.biglogo}>
        </div>
      </div>
      <div>

      </div>
    </div>

  );
}
